config/routes.rb
Rails.application.routes.draw do
  
  
  get 'welcome/index'
  
  get 'mockdrafts/index'
  
  get 'teams/index'

  
  resources :teams
  resources :mockdrafts
  resources :players
  
  resources :mockdrafts do
    resources :mock_draft_comments
  end
  
  resources :players do
    resources :player_comments
  end
  
  resources :teams do
    resources :team_comments
  end
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :player_comments
    validates :name, presence: true, uniqueness: { scope: :name, message: "has already been added" }
    validates :college, presence: true
    validates :position, presence: true
    validates :grade, presence: true
    validates :height, presence: true
    validates :weight, presence: true
    validates :picture_link, presence: true
    validates :highlights_link, presence: true
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    def new
        @player = Player.new
    end
    
    def show
        @player = Player.find(params[:id])
    end
    
    def create
        @player = Player.new(player_params)
        
        if @player.save
            redirect_to @player
        else
            render 'new'
        end
    end
    
    def index
        @players = Player.all
    end
    
    def edit
        @player = Player.find(params[:id])
    end
    
    def update
        @player = Player.find(params[:id])
        
        if @player.update(player_params)
            redirect_to @player
        else
            render 'edit'
        end
    end
    
    def destroy
        @player = Player.find(params[:id])
        @player.destroy
        
        redirect_to players_path
    end
end

private
    def player_params 
        params.require(:player).permit(:name, :college, :position, :grade, :height, :weight, :picture_link, :highlights_link)
    end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/edit.html.erb
<div class="container">
    <div class="nav">
        <div class="navtitle">
            <h2>Links</h2>
        </div>
            <li><%= link_to 'Home', controller: 'welcome' %></li>
            <li><%= link_to 'Teams', controller: 'teams' %></li>
            <li><%= link_to 'Players', controller: 'players' %></li>
            <li><%= link_to 'Create a Mock Draft', new_mockdraft_path %></li>
            <li><%= link_to 'User Mock Drafts', controller: 'mockdrafts' %></li>
    </div>
        
    <div class="main">
        <div class="title">
            <h1>Editing Player</h1>
        </div>
        
        <%= form_for :player, url: player_path(@player), method: :patch do |f| %>
            <% if @player.errors.any? %>
            <div class="error">
            <div id="error_explanation">
                <h2>
                    <%= pluralize(@player.errors.count, "error") %> prohibited
                    this player from being saved:
                </h2>
                <ul>
                    <% @player.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
            </div>
            <% end %>
            <br><br>
            
            <div class="form">
            <p>
                <%= f.label :name %>
                <%= f.text_field :name %>
            </p>
            <p>
                <%= f.label :college %>
                <%= f.text_field :college %>
            </p>
            <p>
                <%= f.label :position %>
                <%= f.text_field :position %>
            </p>
            <p>
                <%= f.label :grade %>
                <%= f.text_field :grade %>
            </p>
            <p>
                <%= f.label :height %>
                <%= f.text_field :height %>
            </p>
            <p>
                <%= f.label :weight %>
                <%= f.text_field :weight %>
            </p>
            <p>
                <%= f.label :picture_link %>
                <%= f.text_field :picture_link %>
            </p>
            <p>
                <%= f.label :highlights_link %>
                <%= f.text_field :highlights_link %>
            </p>
            <p>
                <%= f.submit %>
                <button>
                    <div class="buttontext">
                        <%= link_to "Cancel", controller: 'players' %>
                    </div>
                </button>
            </p>
            </div>
        <% end %>
    </div>
</div>

app/views/players/index.html.erb
<div class="container">
    <div class="nav">
        <div class="navtitle">
            <h2>Links</h2>
        </div>
            <li><%= link_to 'Home', controller: 'welcome' %></li>
            <li><%= link_to 'Teams', controller: 'teams' %></li>
            <li><%= link_to 'Players', controller: 'players' %></li>
            <li><%= link_to 'Create a Mock Draft', new_mockdraft_path %></li>
            <li><%= link_to 'User Mock Drafts', controller: 'mockdrafts' %></li>
    </div>
        
    <div class="main">
        <div class="title"><h1>Players</h1></div>
        <table>
            <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Grade</th>
                <th>Edit Player</th>
                <th>Delete Player</th>
            </tr>
            
            <% @players.each do |player| %>
            <tr>
                <td><%= link_to player.name, player_path(player) %></td>
                <td><%= player.position %></td>
                <td><%= player.grade %></td>
                <td><%= link_to 'Edit', edit_player_path(player) %></td>
                <td><%= link_to 'Delete', 
                        player_path(player),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/players/new.html.erb
<div class="container">
    <div class="nav">
        <div class="navtitle">
            <h2>Links</h2>
        </div>
            <li><%= link_to 'Home', controller: 'welcome' %></li>
            <li><%= link_to 'Teams', controller: 'teams' %></li>
            <li><%= link_to 'Players', controller: 'players' %></li>
            <li><%= link_to 'Create a Mock Draft', new_mockdraft_path %></li>
            <li><%= link_to 'User Mock Drafts', controller: 'mockdrafts' %></li>
    </div>
        
    <div class="main">
        <div class="title">
            <h1>New Player</h1>
        </div>
        <%= form_for :player, url: players_path do |f| %>
        <% if @player.errors.any? %>
            <div class="error">
            <div id="error_explanation">
                <h2>
                    <%= pluralize(@player.errors.count, "error") %> prohibited
                    this player from being saved:
                </h2>
                <ul>
                    <% @player.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
            </div>
        <% end %>
        <br><br>
        
            <div class="form">
            <p>
                <%= f.label :name %>
                <%= f.text_field :name %>
            </p>
            <p>
                <%= f.label :college %>
                <%= f.text_field :college %>
            </p>
            <p>
                <%= f.label :position %>
                <%= f.text_field :position %>
            </p>
            <p>
                <%= f.label :grade %>
                <%= f.text_field :grade %>
            </p>
            <p>
                <%= f.label :height %>
                <%= f.text_field :height %>
            </p>
            <p>
                <%= f.label :weight %>
                <%= f.text_field :weight %>
            </p>
            <p>
                <%= f.label :picture_link %>
                <%= f.text_field :picture_link %>
            </p>
            <p>
                <%= f.label :highlights_link %>
                <%= f.text_field :highlights_link %>
            </p>
            <p>
                <%= f.submit %>
                <button>
                    <div class="buttontext">
                        <%= link_to "Cancel", controller: "players" %>
                    </div>
                </button>
            </p>
            </div>
        <% end %>
    </div>
</div>

app/views/players/show.html.erb
<div class="container">
    <div class="nav">
        <div class="navtitle">
            <h2>Links</h2>
        </div>
            <li><%= link_to 'Home', controller: 'welcome' %></li>
            <li><%= link_to 'Teams', controller: 'teams' %></li>
            <li><%= link_to 'Players', controller: 'players' %></li>
            <li><%= link_to 'Create a Mock Draft', new_mockdraft_path %></li>
            <li><%= link_to 'User Mock Drafts', controller: 'mockdrafts' %></li>
    </div>
    
    <div class="main">
        <div class ="bio">
        <h1>
            <%= @player.name %>
        </h1><br><br>

        <img 
            src=<%= @player.picture_link %>
            style="border: 3px solid #000000;"
        />
        
        <h3>
            College:
            <%= @player.college %>
        </h3>
        
        <h3>
            Position:
            <%= @player.position %>
        </h3>
        
        <h3>
            Grade:
            <%= @player.grade%>
        </h3>
        
        <h3>
            Height:
            <%= @player.height %>
        </h3>
        
        <h3>
            Weight:
            <%= @player.weight %>
        </h3>
        </div><br><br>
        
        <div class="highlights">
        <h3>Highlights:</h3>
        
        <iframe class="html5 video" width="560" height="315"
            style="border: 3px solid #FF0000;"
            src=<%= @player.highlights_link %> frameborder="0" allowfullscreen>
        </iframe>
        </div>
        <br><br>
    
            
        <% if @player.player_comments.exists? %> 
            <div class="comments">
            <h2>Comments</h2>
            <% @player.player_comments.each do |comment| %>
                <div class="individual_comment">
                <p>
                    <strong>Commenter:</strong>
                    <%= comment.commenter %>
                </p>
            
                <p>
                    <strong>Comment:</strong>
                    <%= comment.body %>
                </p>
                </div>
            <% end %>
            </div>
        <% end %>
        
        <br><br>
        
        <div class="newcomments">
        <h2>Add a comment:</h2>
        <%= form_for([@player, @player.player_comments.build]) do |f| %>
            <p>
                <%= f.label :commenter %>
                <%= f.text_field :commenter %>
            </p>
            <p>
                <%= f.label :body %>
                <%= f.text_area :body %>
            </p>
            <p>
                <%= f.submit "Submit" %>
            </p>
        <% end %>
        </div>
        
        
        <br><br>
        <button>
            <div class="buttontext">
                <%= link_to "Back to Players", controller: 'players' %>
            </div>
        </button>
        
    </div>
</div>    